### ISSUE TITLE
Normals orientations

### ISSUE THREAD

**Issue by romaintha** [aboulch/normals_HoughCNN#3]
Hi @aboulch ,
I have been reading the paper, and playing a bit around with the code. There is something that I am wondering about. If I have a look at the normals generated for the test cube, I see that half of the faces of the cube have normals pointing outward, and half of them are pointing inward (see screenshot from CloudCompare).  
![cube](https://user-images.githubusercontent.com/9165318/49570753-2d6ad780-f940-11e8-87d9-31bf3fed3b61.png)

It seems that the orientation of the normals is not random, since on the same face, all normals are coherently oriented. But still from one face to another, the orientation can change. I was wondering how this is handled. I checked a bit the data used for training. and I realized that the geometric shape are all made of 3 faces, with coherently oriented normals (all face normals share the same orientation). 

Can you tell me a bit more about the orientation of the normals? Is it something that the network learns as well? In that case, do you think that changing the training data would allow the network to orient all the normals coherently at the surface of the cube (e.g. all pointing outward)?

**Comment by aboulch** [comment]
Hi,
In the code there is nothing to enforce the normal orientation. The orientation that you obtain is a "side effect of the training" and it was never intended.

In order to compute normal orientation I would recommend something like:
http://geometry.caltech.edu/pubs/MDDCA10.pdf
there is a robust orientation algorithm. But I don't know if there is code online.

**Comment by romaintha** [comment]
Thank you for the answer. I guess there is room to play with the training data then.
I am closing the issue.
